### ISSUE TITLE
Plugin not working along with cypress

### ISSUE THREAD

**Issue by wanbinkimoon** [iFaxity/vite-plugin-istanbul#13]
Cannot make this work here is my config 

`vite.config.js`
```
export default defineConfig({
  plugins: [
    react(),
    vanillaExtractPlugin(),
    istanbul({
      include: path.resolve(__dirname, "./src/*"),
      exclude: ["node_modules", "cypress/"],
      extension: [".ts", ".tsx"],
      requireEnv: true,
    })
  ],
  envPrefix: "REACT_APP_",
  server: {
    port: 5001
  },
  build: {
    outDir: path.resolve(__dirname, "./build"),
    sourcemap: true,
    manifest: true
  },
  resolve: {
    alias: {
      "~": path.resolve(__dirname, "./src")
    }
  }
});
```

`cypress/plugins/index.js`
```
module.exports = (on, config) => {
  on("dev-server:start", options =>
    startDevServer({
      options,
      viteConfig: {
        clearScreen: false,
        configFile: path.join(__dirname, "../../vite.config.js")
      }
    })
  );

  codeCoverageTask(on, config);
  return config;
};
```

`cypress/support/index.js`
```
import "./commands";
import "@cypress/code-coverage/support";
```

cypress work as expected but no `window.__coverage__` is found in dev mode 

I receive this error
```
⚠️ file /Users/[username]/Developer/[client]/[project]/frontend/.nyc_output/out.json has no coverage information
Did you forget to instrument your web application? Read https://github.com/cypress-io/code-coverage#instrument-your-application
```

**Comment by wanbinkimoon** [comment]
Apparently the plugin works only in `component testing` mode 

Closing the issue, please update the docs as it's not stated anywhere.

**Comment by iFaxity** [comment]
Hi @wanbinkimoon, absolutely. I will look into why it is only working in the component testing mode. It might be how cypress sends in env variables to the plugin. I am fairly sure this has worked in the past with previous versions of the package.

**Comment by wanbinkimoon** [comment]
@jordan-boyer I arrived at the same conclusion with less precision than yours, dunno about the `start-server-and-test preview http://127.0.0.1:5050/ 'cypress open'` command but yep cypress is definitely running the code in the `dist` folder while the coverage is not there. 

+1 on the diagnosis, @iFaxity any idea how we should fix this?

**Comment by iFaxity** [comment]
In @jordan-boyer's case Vite  seems to be running in preview mode `start-server-and-test preview http://127.0.0.1:5050/ 'cypress open'`. Which launches Vite as only a static server which serves the output from build.

Is this the case for you aswell @wanbinkimoon?

This plugin has a restriction to only run in the "serve" mode of Vite. This is to prevent accidental builds to dist with code coverage. This could be altered but will probably break in some environments. 

In this case it would be safer to add a major version which allows for instrumentation to prebuilt sources.

**Comment by jordan-boyer** [comment]
@iFaxity I think i understand the solution, do you want me to do a PR about it ?

**Comment by iFaxity** [comment]
@jordan-boyer Sure go ahead, that would be greatly appreciated.

**Comment by jordan-boyer** [comment]
I'm still missing something, i'm able to instrument the code in build mode but cypress is looking for the coverage in window.__coverage__ but i don't understand how it is injected ^^' 

I've tried to inject it in the index.html with the `transformIndexHtml` but global.__coverage__ is always undefined

**Comment by wanbinkimoon** [comment]
@jordan-boyer do you have an example we could look at and sort out something together?

**Comment by wanbinkimoon** [comment]
also https://github.com/cypress-io/code-coverage/issues/539

**Comment by jordan-boyer** [comment]
Ofc, here what I've done : https://github.com/jordan-boyer/vite-plugin-istanbul/tree/feat/force-instrument-in-build-mode

In your project you juste have to do `plugins: [vue(), istanbul({ forceBuildInstrument:  true })],`.

I think i'm on the right track to solve the problem but i'm just missing one critical piece

**Comment by jordan-boyer** [comment]
Well here it is : https://github.com/iFaxity/vite-plugin-istanbul/pull/15

**Comment by iFaxity** [comment]
#15 just released as part of v2.5.0.

Thanks for the great work.

**Comment by wanbinkimoon** [comment]
I'll test it in the next hours and give you feedbacks on this, in the mean time thank you for the effort <3

**Comment by madiodio** [comment]
Can anybody confirm this is actually working ? Cc @wanbinkimoon

**Comment by wanbinkimoon** [comment]
yes it is :)

**Comment by belwalshubham** [comment]
after integrate cypress code coverage in nuxt , Though I'm getting options.ssr value as both true & false for different files, I got this error on my console ,
[Vue warn]: Hydration node mismatch:
Client vnode:..
can anyone help me on this ?

**Comment by iFaxity** [comment]
Hi @belwalshubham, please make a new issue instead of commenting on a closed issue.

Also provide more information or a repository where the error can be reproduced
